site_name: TaskerPy
repo_url: https://github.com/brunodavi/tasker.py
repo_name: brunodavi/tasker.py
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist

  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - styles/extra.css

watch:
   - src/tasker

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [src/tasker]
        options:
          show_submodules: true

extra:
  commands:
    install: pip install git+https://github.com/brunodavi/tasker.py
