[tool.pdm]
[tool.pdm.scripts]
test.cmd = "pytest -vv -s"
test.env_file = '.env'

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.3.1",
]

[project]
name = "tasker.py"
version = "0.2.0"
description = "Automatize seu android com python"
authors = [
    {name = "Bruno Davi", email = "48166556+brunodavi@users.noreply.github.com"},
]

dependencies = [
    "httpx>=0.24.1",
    "cython>=3.0.0",
    "lxml>=4.9.3",
]

requires-python = ">=3.10"
license = {text = "MIT"}