name: Test Python 3.9 | 3.10 | 3.11

on:
  push:
    branches: [main]
    paths:
      - 'pyproject.toml'
      - 'pdm.lock'
      - 'src/**/*.py'
      - 'test/**/*.py'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'pdm.lock'
      - 'src/**/*.py'
      - 'test/**/*.py'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Configurar PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Instalar dependências da aplicação
        run: pdm install

      - name: Instalar dependências de teste
        run: pdm install -G test

      - name: Executar testes
        run: pdm test -k 'not action'
